### ISSUE TITLE
Skip Login try to get data from fake user id on "read more"

### ISSUE THREAD

**Issue by mikecastrodemaria** [ionicthemes/ionic3-wordpress-integration#16]
I try to display post content, by using the "skip login" link on the home, I well receive the list of my post, but when I click "read more" of a post, the detail post is displayed, but a loader stay stuck on overload.

From the debugger, I can see there is a login try to get data from fake user id.

Why the "skip login" is not recorder as choice and avoid, this ?

**Comment by djabif** [comment]
Maybe it's related to the comments section...? The app checks if there is a logged user which is able to comment.
