### ISSUE TITLE
Implement WordPressService in other apps

### ISSUE THREAD

**Issue by davidperezgar** [ionicthemes/ionic3-wordpress-integration#2]
Hello!  It's very nice your App!
I saw that you've not used wp-api-angular, which is nice, but I'm getting WordPressService for other App and is getting this error.

Error: StaticInjectorError[WordpressService]: 
  StaticInjectorError[WordpressService]: 
    NullInjectorError: No provider for WordpressService!

Do you know if something is missing? Thanks!

**Comment by djabif** [comment]
Hello @davidperezgar, this is an ionic app that uses the Wordpress REST API to get your posts and blog data. `WordpressService` is the name of the Angular service we created to host the methods that will communicate with the WP API. 
Your error suggests that you didn't declare the Service on your module as a Provider. (check our app.module to see how to do it)

This code is part of a tutorial from https://ionicthemes.com which I will finish and publish in the upcoming days.

**Comment by davidperezgar** [comment]
Thanks @djabif !
