### ISSUE TITLE
i have an issue

### ISSUE THREAD

**Issue by rynProject** [ionicthemes/ionic3-wordpress-integration#23]
npm ERR! code E404
npm ERR! 404 Not Found: ansi-styles@2.2.0

how i can fix it?

**Comment by Dahouo** [comment]
Hello here I have the same issue.
`npm ERR! code E404
npm ERR! 404 Not Found: ansi-styles@2.2.0`
Any solution ? The dependancy seems not more on npm

**Comment by djabif** [comment]
Hi, we are working to update this repo to Ionic 4 and update everything.

**Comment by Velfix** [comment]
Do you have any news about this?

**Comment by djabif** [comment]
The project is now updated to Ionic and Angular latest versions!
