### ISSUE TITLE
Unable to login to my site using "ionic3-wordpress-integration"

### ISSUE THREAD

**Issue by tirtharaydesigner** [ionicthemes/ionic3-wordpress-integration#3]
Hi, my name is Tirtha. I'm from Brasil .. Have you have the " ionic3-wordpress-integration "  course ? I'm making a simple app for my church. I am using/ followed your script to create the app. But I am running into some problem with login . right now it connects with app.ieqjardimcidade1.com site.. and loads up the posts . But I am unable to login  with na user.  I have followed the seps  for JSON Web Token (JWT) but i am unable to do it. 

Can you please help me here? I have installed the plugin onto my wordpress site and did everything.   

Your help is really appreciated!
Thank you for Reading
Tirtha

**Comment by djabif** [comment]
Hello Tirtha you can check the tutorial in  https://ionicthemes.com/tutorials/about/ionic-wordpress-integration
