### ISSUE TITLE
How to display post from specific category

### ISSUE THREAD

**Issue by sayseee** [ionicthemes/ionic3-wordpress-integration#4]
Hello,

I have been using you code and now i have issues in creating a specific category page and its posts.
e.g I have a WorksPage in my App. I want to display all posts from thecategory (works) with (1) in my wordpress site to the WorksPage in the app.

Thank you

**Comment by sadikyalcin** [comment]
If I understand correctly, you want to display posts from a specific category? If that's the case then the URL would be: `yoursite.com/wp-json/wp/v2/posts/?categories=[categoryid]`

**Comment by djabif** [comment]
Yes, yoursite.com/wp-json/wp/v2/posts/?categories=[categoryid] will do that. You can learn more in the API docs https://developer.wordpress.org/rest-api/reference/posts/#list-posts
If you want a working example of this, I added this feature to [Ion2FullApp ELITE latest version](https://ionicthemes.com/product/ion2fullapp-full-ionic2-app-template-elite-version).
