### ISSUE TITLE
How can I enable Push Notifications

### ISSUE THREAD

**Issue by sayseee** [ionicthemes/ionic3-wordpress-integration#5]
Hello, I need help with code that can enable push notifications whenever there is  a new post.

Thx

**Comment by sayseee** [comment]
When do you hope to add the push notifications functionality?

**Comment by djabif** [comment]
We don't plan to add push notifications to this ionic 3 tutorial. However, you can find it implemented  for Ionic 1 in IonWordpress: https://ionicthemes.com/product/ionwordpress-wordpress-mobile-app. You can check the ionwordpress template documentation to see how we did it.
