### ISSUE TITLE
 installation error

### ISSUE THREAD

**Issue by henriqueguedes-developer** [ionicthemes/ionic3-wordpress-integration#6]
installation error

I tried to use your project here but it did not work out for me.

kakaroto@kakaroto:~/teste$ clear

kakaroto@kakaroto:~/teste$ git clone  https://github.com/ionicthemes/ionic3-wordpress-integration.git
Cloning into 'ionic3-wordpress-integration'...
remote: Counting objects: 149, done.
remote: Total 149 (delta 0), reused 0 (delta 0), pack-reused 149
Receiving objects: 100% (149/149), 1.94 MiB | 968.00 KiB/s, done.
Resolving deltas: 100% (30/30), done.
kakaroto@kakaroto:~/teste$ ls
ionic3-wordpress-integration
kakaroto@kakaroto:~/teste$ cd ionic3-wordpress-integration/
kakaroto@kakaroto:~/teste/ionic3-wordpress-integration$ npm install
npm WARN deprecated cordova-plugin-console@1.1.0: This plugin has been deprecated since it is now included in the latest versions of cordova-ios
npm WARN deprecated babili@0.1.2: babili has been renamed to babel-minify. Please update to babel-minify
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-m+qzzcn7KUxEmd1gMbchF+Y2eIUbieUaxkWtptyHywrX0rE8QEYqPC07Vuy4Wm32/xE16NcdBctb8S0Xe/5IeQ== integrity checksum failed when using sha512: wanted sha512-m+qzzcn7KUxEmd1gMbchF+Y2eIUbieUaxkWtptyHywrX0rE8QEYqPC07Vuy4Wm32/xE16NcdBctb8S0Xe/5IeQ== but got sha1-No8lEtefnUb9/HE0mueHi7weuVw=. (25587 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> node-sass@4.5.3 install /home/kakaroto/teste/ionic3-wordpress-integration/node_modules/@ionic/app-scripts/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/kakaroto/.npm/node-sass/4.5.3/linux-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/kakaroto/teste/ionic3-wordpress-integration/node_modules/@ionic/app-scripts/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.5.3 postinstall /home/kakaroto/teste/ionic3-wordpress-integration/node_modules/@ionic/app-scripts/node_modules/node-sass
> node scripts/build.js

Binary found at /home/kakaroto/teste/ionic3-wordpress-integration/node_modules/@ionic/app-scripts/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN @ionic-native/native-storage@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.2.tgz: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/@ionic/app-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1523 packages in 67.218s
kakaroto@kakaroto:~/teste/ionic3-wordpress-integration$ ionic serve
Error: Cannot find module '@angular/tsc-wrapped/src/tsc'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kakaroto/teste/ionic3-wordpress-integration/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:7:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by djabif** [comment]
Check https://github.com/ionic-team/ionic/issues/12357. 
It looks like you need to Update npm to last version
