### ISSUE TITLE
How do I add a working pull to refresh feature?

### ISSUE THREAD

**Issue by sayseee** [ionicthemes/ionic3-wordpress-integration#8]
Hello,

How do I add the pull to refresh feature?
Am using this code and it seems not to be loading new posts
```

  doRefresh(refresher) {
    console.log('Begin async operation', refresher);

    setTimeout(() => {
      console.log('Async operation has ended');
      refresher.complete();
    }, 2000);
  }

```
Any ideas?

**Comment by djabif** [comment]
Hello @sayseee you can find a ionic 3 starter app with lots of features in https://ionicthemes.com/product/ion2fullapp-full-ionic2-app-template-elite-version

**Comment by djabif** [comment]
@sayseee you can also find the refresher or pull to refresh documentation in Ionic Framework Ui Components page: https://ionicframework.com/docs/api/components/refresher/Refresher/
