### ISSUE TITLE
Problem with register

### ISSUE THREAD

**Issue by magnogcs** [ionicthemes/ionic3-wordpress-integration#9]
Hi!
I'm having a problem when I try to sign up. The login page is working when I login with the default credentials from my local WordPress (user root pass root), but the register isn't working, all I see is JSON: **[jwt_auth] empty_username**. And when I send directly values it shows me the mistake as if I was trying to login (invalid username), could this be a problem with my jwt-auth settings?

my wp .htaccess:
`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
RewriteBase /wordpress/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /wordpress/index.php [L]
</IfModule>`

wp-config.php:
[...]
`define('JWT_AUTH_CORS_ENABLE', true);
define('JWT_AUTH_SECRET_KEY', 'your-top-secrect-key');`

**Comment by nabilzidane** [comment]
Hi, @magnogcs 
No it's not. you need to know that only admin can create new users, so you have to add some details : 
Go to `PROJECT_FILES/src/pages/register/register.ts` and change the following details : 
```
32    onSubmit(values){
33      var username: '**aa**'; // this should be an administrator Username
34      var password: '**aa**'; // this should be an administrator Password
```
aa values must be your admin identification.

The App will login as an admin and post a new user with the informations provided in the register form.

**Comment by djabif** [comment]
That's correct. Thanks @nabilzidane for the clarification.
